name: Test
on: 
  push:
    branches:
      - master
      - add-action

permissions:
  contents: write
  pull-requests: write

jobs:
  semver-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - uses: actions/checkout@v3
        with:
          repository: zckv/semantic-versioning-example
          path: ./pyproject/
          ref: master
      - uses: actions/checkout@v3
        with:
          path: ./pyaction/
      # Test the action with no enabled steps.
      - name: Test Action
        uses: ./pyaction/
        with:
          base: master
