name: Test
on: 
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  semver-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - uses: actions/checkout@v3
      # Test the action with no enabled steps.
      - name: Test Action
        uses: .
